"""Pure scientific mechanisms and contracts (no Mesa or interface dependencies)."""

from .actions import allow_all, literal_local_policy, resolve_actions
from .cognition import copy_observation, direct_observation
from .ecology import (
    InvariantViolationError,
    advance_correlated_event,
    apply_recovery,
    apply_simultaneous_damage,
    draw_event,
    draw_independent_hits,
    draw_uniform_position,
    initialize_recovery_state,
    initialize_resources,
    regenerate,
    relax_resources,
    start_correlated_event,
    von_neumann_neighbors,
)
from .interfaces import DecisionPolicy, InstitutionalGate, ObservationSystem, PhysicalResolver
from .physiology import apply_metabolism
from .types import (
    ActionIntent,
    ActionKind,
    ActionResolution,
    AgentSnapshot,
    AgentState,
    AgentTransitionRecord,
    BeliefState,
    CellDamageApplication,
    CohortRecord,
    DamageBatch,
    DamageParameters,
    EventCellExposure,
    EventRecord,
    GateDecision,
    ModelRecord,
    Observation,
    RecoveryState,
    ResolutionBatch,
    ShockEventSnapshot,
    ShockEventState,
    ShockEventStatus,
    ShockScope,
    ShockTerminationReason,
    WavefrontAdvance,
)

__all__ = [
    "ActionIntent",
    "ActionKind",
    "ActionResolution",
    "AgentSnapshot",
    "AgentState",
    "AgentTransitionRecord",
    "BeliefState",
    "CellDamageApplication",
    "CohortRecord",
    "DamageBatch",
    "DamageParameters",
    "DecisionPolicy",
    "EventRecord",
    "EventCellExposure",
    "GateDecision",
    "InstitutionalGate",
    "InvariantViolationError",
    "ModelRecord",
    "Observation",
    "ObservationSystem",
    "PhysicalResolver",
    "ResolutionBatch",
    "RecoveryState",
    "ShockEventState",
    "ShockEventStatus",
    "ShockEventSnapshot",
    "ShockScope",
    "ShockTerminationReason",
    "WavefrontAdvance",
    "allow_all",
    "apply_metabolism",
    "apply_recovery",
    "apply_simultaneous_damage",
    "advance_correlated_event",
    "copy_observation",
    "direct_observation",
    "draw_event",
    "draw_independent_hits",
    "draw_uniform_position",
    "initialize_resources",
    "initialize_recovery_state",
    "literal_local_policy",
    "regenerate",
    "relax_resources",
    "resolve_actions",
    "start_correlated_event",
    "von_neumann_neighbors",
]
